### PR TITLE
Fix removing declarator type for unsafe-wrap mode. Fixes #175

### LINKED ISSUE #175: "unsafe-wrap" mode crashes when a type is referenced from a variable
[Here](https://github.com/billyjanitsch/babel-rm-proptypes-crash)'s a minimal repro.

The code below causes the plugin to crash when `mode` is set to `"unsafe-wrap"`:

```js
import * as React from 'react'
import PropTypes from 'prop-types'

const sharedPropType = PropTypes.number

export default class Foo extends React.Component {
  static propTypes = {
    bar: sharedPropType,
  }
}
```

Here's the stack trace:

```
TypeError: @babel/template placeholder "NODE": Property expression of ExpressionStatement expected node to be of a type ["Expression"] but instead got "VariableDeclarator"
    at Object.validate (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/types/lib/definitions/utils.js:128:13)
    at validate (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.ExpressionStatement (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/types/lib/builders/generated/index.js:293:31)
    at applyReplacement (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/template/lib/populate.js:92:29)
    at metadata.placeholders.slice.reverse.forEach.placeholder (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/template/lib/populate.js:42:7)
    at Array.forEach (<anonymous>)
    at populatePlaceholders (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/template/lib/populate.js:40:43)
    at arg (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/template/lib/string.js:22:51)
    at arg (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/template/lib/builder.js:77:14)
    =============
    at PluginPass.Program (/Users/billy/work/babel-rm-proptypes-crash/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:160:31)
    at newFn (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/Users/billy/work/babel-rm-proptypes-crash/node_modules/@babel/traverse/lib/context.js:146:19)
```

### PR DESCRIPTION
**Pull request by jjow**
This is a fix for https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/issues/175. @lencioni and I figured out that when removing newly unused identifiers in `unsafe-wrap` mode, we should just use the wrapTemplate instead of the unwrapTemplate.

For example, `const sharedPropType = PropTypes.number;` would be transformed into:

unwrapTemplate:
```
if (process.env.NODE_ENV !== "production") {
  const sharedPropType = PropTypes.number; // NOTE the scope issue here! 
}
```

wrapTemplate:
```
const sharedPropType = process.env.NODE_ENV !== "production" ? PropTypes.number : {};
```

Closes #175

### CODE REVIEW

File: src/remove.js [hunk 1]
```diff
@@ -105,23 +105,15 @@ export default function remove(path, globalOptions, options) {
         break
 
       case 'declarator':
-        if (mode === 'unsafe-wrap') {
```
Comment (lencioni) [inline src/remove.js]: For posterity, the reason we decided that the wrap behavior is a good choice for the unsafe-wrap mode here is because const and let are block-scoped, and we don't want to change the scoping or semantics of the original code.

File: test/fixtures/bugfix-175/expected-unsafe-wrap-es6.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+const sharedPropType = process.env.NODE_ENV !== "production" ? PropTypes.number : {};
```
Comment (oliviertassinari) [inline test/fixtures/bugfix-175/expected-unsafe-wrap-es6.js]: I'm surprised we handle this variable.

Comment (lencioni) [reply test/fixtures/bugfix-175/expected-unsafe-wrap-es6.js]: This is part of the work I did in https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/pull/146

If we don't wrap it, the minifier won't fully remove it because it might have side-effects (e.g. function calls or getters).

image

Handling this with the wrap behavior allows it to be minified out completely:

image

There might be a way to use the `/*@__PURE__*/` annotation instead to produce the desired result, which I think would clean up a lot of this plugin, but I was unable to get that to work effectively enough in the REPL.
